### PR TITLE
Update zenoh to `v0.7.0-rc`

### PR DESCRIPTION
**Pull request by phil-opp**
This PR updates the `zenoh` dependency to the latest crates.io version. We were using a pinned commit before.

The new zenoh release should improve performance, which hopefully also makes our project faster. Another advantage of this change is that it removes the last git dependency, so we should be able to publish our crate to crates.io afterwards.

### CODE REVIEW

**Comment by juntao** [comment]
flows summarize

**Comment by juntao** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

These are reviews for software source code patches. The first patch updates project dependencies and introduces code changes. Reviewers suggest examining the changes carefully to ensure they are compatible with existing functionality. The second patch fixes an issue with topic names by making a straightforward code change. The third patch has made various changes to syntax and formatting, which could introduce bugs or compatibility issues. Reviewers suggest testing the patch before merging. The fourth patch addresses warnings and suggestions and makes some code improvements without having any potential problems.

## Details

### Commit 1
The patch updates the project's dependency to zenoh-0.7.0-rc. There are changes to multiple files that include updates to dependency versions, code changes such as addition of new nodes and handlers, changes to file names and method calls. From this patch, it is difficult to identify potential problems without understanding the project's context and requirements. However, it is advisable to review the changes carefully to ensure they do not break existing functionality and adhere to best practices.

### Commit 2
The patch fixes a problem with leading slashes in topic names which is not allowed in zenoh 0.7. Both `src/bin/logger.rs` and `src/lib.rs` files have been modified to replace `/` with no leading slashes at the beginning of the topic path. There do not appear to be any potential problems with this code change. The patch seems to be a straightforward fix for the problem at hand.

### Commit 3
The key changes in the patch are running `cargo clippy --fix` on the project, which has made changes to several files. These changes include fixing string formatting issues, correcting function arguments, and making other minor syntax changes. Potential problems in the patch could include introducing new bugs or breaking existing functionality. It would be advisable to review the changes in detail and test thoroughly before merging the patch.

### Commit 4
This GitHub patch resolves warnings and clippy suggestions for the codebase. 

The most notable change in the patch is that some `try_into` calls were removed, which were converting strings to socket addresses, and the error handling of some calls to `await` was improved by mapping error cases. 

There are no potential problems in the patch.

**Comment by phil-opp** [comment]
@juntao These summaries are a nice idea, but they seems to be incorrect in multiple places. For example:



> code changes such as addition of new nodes and handlers

We don't introduce any new nodes or handlers in this PR.



> changes to file names

I don't see any changed file names either..


> correcting function arguments

We don't change any function arguments.



> some `try_into` calls were removed, which were converting strings to socket addresses

The removed `try_into` calls were converting from string to string, so they were unnecessary and could be removed without any semantic changes.


Also, the summary is quite verbose and repetitive. I don't think that sentences such as "These are reviews for software source code patches" or "Reviewers suggest testing the patch before merging" add much value.

I hope this feedback helps to improve the bot's output!

**Comment by phil-opp** [comment]
This PR seems ready to be merged.

**Comment by juntao** [comment]
Thank you! The prompts definitely need improvement to make ChatGPT summarize better! I would also make it more focused on potential risks and errors. Another way to improve it is to incorporate the discussion thread into the prompt -- it currently only has the patch file to work with. 

Lots of potential improvements. I will probably re-generate summaries here -- feel free to remove them if they start to clutter the timeline. :) Please keep giving us feedbacks. 

Cheers
Michael

> @juntao These summaries are a nice idea, but they seems to be incorrect in multiple places. For example:
> 
> 
> 
> 
> 
> 
> 
> > code changes such as addition of new nodes and handlers
> 
> 
> 
> We don't introduce any new nodes or handlers in this PR.
> 
> 
> 
> 
> 
> 
> 
> > changes to file names
> 
> 
> 
> I don't see any changed file names either..
> 
> 
> 
> 
> 
> > correcting function arguments
> 
> 
> 
> We don't change any function arguments.
> 
> 
> 
> 
> 
> 
> 
> > some `try_into` calls were removed, which were converting strings to socket addresses
> 
> 
> 
> The removed `try_into` calls were converting from string to string, so they were unnecessary and could be removed without any semantic changes.
> 
> 
> 
> 
> 
> Also, the summary is quite verbose and repetitive. I don't think that sentences such as "These are reviews for software source code patches" or "Reviewers suggest testing the patch before merging" add much value.
> 
> 
> 
> I hope this feedback helps to improve the bot's output!

**Pull request merged**
